export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'


export const GET_BRANDS = 'GET_BRANDS'
export const BRANDS_GOT = 'BRANDS_GOT'


export const ADD_SUBRANDS = 'ADD_SUBRANDS'
export const SUBRANDS_ADDED = 'SUBRANDS_ADDED'
